import type { NextPage } from 'next';
import Head from 'next/head';
// import Feature from '../components/Feature';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pool Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-green-300 to-purple-400">
        <Hero />
        {/* <Feature /> */}
      </main>
    </>
  );
};

export default Home;
