import type { NextPage } from 'next';
import Head from 'next/head';

const Test: NextPage = () => {
  return (
    <>
      <Head>
        <title>CIEL Stake Pool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-screen bg-gradient-to-br from-green-300 via-blue-500 to-purple-600">
        <div className="hero-content text-center">
          <div className="">
            <h1 className="text-5xl font-bold">Coming Soon</h1>
            <p className="py-6 max-w-md mx-auto">
              このページは現在開発中です。
            </p>
            <div className="py-6"></div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Test;
